build:
  uv run summary.py -u 1bharath-yadav -n Bharath 
  uv run update_readme.py

week := `date +%F`

deploy:
  gh release upload main {{week}}/podcast-{{week}}.mp3
  gh release upload main --clobber podcast.xml
